export const SHOW_LOGIN = "SHOW_LOGIN";
export const HIDE_LOGIN = "HIDE_LOGIN";

export const TOGGLE_PLEDGE = "TOGGLE_PLEDGE";

export const ADD_COMMITMENT_SUCCESS = "ADD_COMMITMENT_SUCCESS";
export const ADD_COMMITMENT_FAILED = "ADD_COMMITMENT_FAILED";
export const DELETE_COMMITMENT_SUCCESS = "DELETE_COMMITMENT_SUCCESS";
export const DELETE_COMMITMENT_FAILED = "DELETE_COMMITMENT_FAILED";
