export const SHOW_LOGIN = "SHOW_LOGIN";
export const HIDE_LOGIN = "HIDE_LOGIN";
export const CLAIMS_UPDATE = "CLAIMS_UPDATE";

export const SHOW_NAV_DRAWER = "SHOW_NAV_DRAWER";
export const HIDE_NAV_DRAWER = "HIDE_NAV_DRAWER";
export const SET_TITLE = "SET_TITLE";

export const ADD_COMMITMENT_SUCCESS = "ADD_COMMITMENT_SUCCESS";
export const ADD_COMMITMENT_FAILED = "ADD_COMMITMENT_FAILED";
export const DELETE_COMMITMENT_SUCCESS = "DELETE_COMMITMENT_SUCCESS";
export const DELETE_COMMITMENT_FAILED = "DELETE_COMMITMENT_FAILED";

export const INCREMENT_COUNTER_SUCCESS = "INCREMENT_COUNTER_SUCCESS";
export const INCREMENT_COUNTER_FAILED = "INCREMENT_COUNTER_FAILED";
