export const SHOW_LOGIN = "SHOW_LOGIN";
export const HIDE_LOGIN = "HIDE_LOGIN";
export const CLAIMS_UPDATE = "CLAIMS_UPDATE";

export const SET_FORM_DATA = "SET_FORM_DATA";

export const SHOW_NAV_DRAWER = "SHOW_NAV_DRAWER";
export const HIDE_NAV_DRAWER = "HIDE_NAV_DRAWER";
export const SET_TITLE = "SET_TITLE";

export const ADD_PLEDGE_SUCCESS = "ADD_PLEDGE_SUCCESS";
export const ADD_PLEDGE_FAILED = "ADD_PLEDGE_FAILED";
export const UPDATE_PLEDGE_SUCCESS = "UPDATE_PLEDGE_SUCCESS";
export const UPDATE_PLEDGE_FAILED = "UPDATE_PLEDGE_FAILED";
export const DELETE_PLEDGE_SUCCESS = "DELETE_PLEDGE_SUCCESS";
export const DELETE_PLEDGE_FAILED = "DELETE_PLEDGE_FAILED";

export const ADD_COMMITMENT_SUCCESS = "ADD_COMMITMENT_SUCCESS";
export const ADD_COMMITMENT_FAILED = "ADD_COMMITMENT_FAILED";
export const DELETE_COMMITMENT_SUCCESS = "DELETE_COMMITMENT_SUCCESS";
export const DELETE_COMMITMENT_FAILED = "DELETE_COMMITMENT_FAILED";

export const INCREMENT_COUNTER_SUCCESS = "INCREMENT_COUNTER_SUCCESS";
export const INCREMENT_COUNTER_FAILED = "INCREMENT_COUNTER_FAILED";

// Validations
export const MIDDLEWARE_VALIDATE = "MIDDLEWARE_VALIDATE";
export const CREATE_FIELD = "CREATE_FIELD";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const VALIDATE_FIELD = "VALIDATE_FIELD";
